#!/bin/sh
#
# PROVIDE: tornadows
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf[.local] to enable esb server
#
# tornadows_enable (bool):            Set to "NO" by default.
#                                     Set it to "YES" to enable esb.
# tornadows_config (str):             default: {tornadows_home}/server.ini
#                                     Set to the full path of the config file
# tornadows_home (str):               default: /esb
#                                     Set to the full path of the esb home 
# tornadows_flags (str):              Set to "" by default.
#				      Extra flags passed to start command.
# tornadows_pid (str):                default: /esb/run/esb.pid
#                                     Set to the full path of the esb pid file
# tornadows_user (str):               Default user account to run with (default: www).

. /etc/rc.subr

name="tornadows"
rcvar=tornadows_enable
load_rc_config $name

: ${tornadows_enable:="NO"}
: ${tornadows_home="/esb"}
: ${tornadows_config="${tornadows_home}/server.ini"}
: ${tornadows_user="www"}
: ${tornadows_pid="${tornadows_home}/run/esb.pid"}

command="/usr/local/bin/python2.7"
pidfile="${tornadows_pid}"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

tornadows_start()
{
  chdir ${tornadows_home}
  /usr/sbin/daemon -f -u ${tornadows_user} ${command} ${rc_flags} ${tornadows_home}/server.py -c ${tornadows_config}
  echo "${name} started"
}

tornadows_stop()
{
  pid=$(check_pidfile $pidfile $command)
  if [ -z "$pid" ]; then
     echo "Nothing to stop"
  else
      list_to_kill=`pgrep -P ${pid}`
      kill ${pid}
      for i in $list_to_kill
      do
         kill ${i}
      done
      rm ${pidfile}
      echo "${name} stopped"
  fi
}

tornadows_status()
{
  pid=$(check_pidfile $pidfile $command)
  if [ -z "$pid" ]; then
     echo "${name} is NOT running"
  else
     echo "${name} is running, PID ${pid}"
  fi
}


load_rc_config $name
run_rc_command "$1"
